### PR TITLE
Added image url of product to output.

### PR DESCRIPTION
**Pull request by HakanKartal**
I needed images of products and spent about 3 hours figuring it out. Image url is one of 4 in the `images` key. I have chosen the first index wich has the highest resolution.

There is mostlikely a better way of doing this, but this works, feel free to do whatever you think would be a better addition.

### CODE REVIEW

**Comment by rkalis** [comment]
Very nice @HakanKartal! Does every product have a product image? If not, perhaps it should account for the case that the field is undefined for some products. If all products have an image, it should be fine like this.

**Comment by HakanKartal** [comment]
Hey @rkalis!
Sorry for my delayed response!
I've since noticed that indeed (for some reason) not every response contains an image, or any sort of static link for said product (despite the product having one on `ah.nl`). However, every possible response _should_ have one. That being said, `50` out of `21909` products dont seem to contain an image, although this number decreases by the day. I've added a case for it nonetheless.

**Comment by rkalis** [comment]
Thanks for looking into it and adding these changes to the PR. I'll merge and publish them.

**Comment by rkalis** [comment]
It took a bit longer to publish it to PyPI. But `v0.2.1` is live (https://pypi.org/project/appiepy/0.2.1/).

**Pull request merged**
