### PR TITLE
Add extra discount info

### PR DESCRIPTION
**Pull request by ghost**
Useful for when you for example need to inform on which type of discount is provided.

Discount type: e.g. "2 voor 1", "2e halve prijs"
Discount period: e.g. "t/m maandag", "vanaf dinsdag"

### CODE REVIEW

**Comment by rkalis** [comment]
Awesome, great addition! I can't find any examples of products that list the discount period, do you have any examples?

**Comment by ghost** [comment]
Thanks! I just checked and indeed the periods are not mentioned anymore on a lot of products, but I did find this [vegan burger one](https://www.ah.nl/producten/product/wi397365/ah-vegetarische-burger-deluxe). It probably only shows it when it is in a set number of days from ending/starting. It's still very useful though because it helps distinguish currently active discounts from future ones.

**Comment by rkalis** [comment]
I see, cool! Thanks for the contribution!

**Comment by rkalis** [comment]
Published in `0.2.4`.

**Pull request merged**
