### PR TITLE
fix nutrition parsing on "less than"

### PR DESCRIPTION
**Pull request by ricktav**
This would fix the issue parsing nutrition being stated as "less than" with a < character.

### CODE REVIEW

**Comment by rkalis** [comment]
Awesome, thanks for the fix, looks good! Will merge and publish a new version after the weekend.

**Comment by ricktav** [comment]
Thanks!
________________________________
Van: Rosco Kalis ***@***.***>
Verzonden: donderdag 15 april 2021 18:51
Aan: rkalis/AppiePy ***@***.***>
CC: ricktav ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rkalis/AppiePy] fix nutrition parsing on "less than" (#11)


Awesome, thanks for the fix, looks good! Will merge and publish a new version after the weekend.

**Comment by rkalis** [comment]
Thanks again. Just published v0.2.3 with the fix included.

**Comment by ricktav** [comment]
Great Rosco, thanks.

Op vr 16 apr. 2021 om 19:15 schreef Rosco Kalis ***@***.***>

**Pull request merged**
